export { WorkstationLayout } from './WorkstationLayout'
export { WorkstationSidebar } from './WorkstationSidebar'
export { WorkstationMainContent } from './WorkstationMainContent'
export { WorkstationInsightsPanel } from './WorkstationInsightsPanel'
export { QuickStatsCard } from './QuickStatsCard'
export { SavedViewsButtons } from './SavedViewsButtons'
export { WorkstationIntegrated } from './WorkstationIntegrated'
export { RecommendedActionsPanel } from './RecommendedActionsPanel'

export type { WorkstationLayoutProps, WorkstationSidebarProps, WorkstationMainContentProps, WorkstationInsightsPanelProps } from '../../types/workstation'
